components-api: "1.1"
builds:
  - image: "node:16-alpine"
    workdir: /tmp/build
    script:
      - npm i
      - npm run build
    artifacts:
      - /tmp/build/dist
image: "node:16-alpine"
workdir: /home/app
envs:
  NPM_CONFIG_LOGLEVEL: warn
needed_envs: []
# if not defined use the lenra.install.sh
script: [npm i --omit=dev]
watchdog:
  target_dir: /usr/bin/
  envs:
    cgi_headers: "true"
    fprocess: node server.js
    mode: http
    upstream_url: "http://127.0.0.1:3000"
    port: "3333"
    exec_timeout: 10s
    write_timeout: 15s
    read_timeout: 15s
    prefix_logs: "false"
