componentsApi: "1.1"
builders:
  - name: build-ts
    image: "node:16-alpine"
    workdir: /tmp/build
    copySources: true
    rootScript:
      - addgroup -S app
      - adduser -S -g app app
      - chmod -R 777 ./
    script:
      - npm i
      - rm -Rf node_modules
image: "node:16-alpine"
workdir: /home/app
envs:
  NPM_CONFIG_LOGLEVEL: warn
needed_envs: []
rootScript:
  # - apk --no-cache add curl ca-certificates
  - addgroup -S app
  - adduser -S -g app app
script: [npm i --omit=dev]
artifacts:
  - builder: build-ts
    source: /tmp/build/
    destination: /home/app/
watchdog:
  targetDir: /usr/bin/
  params:
    cgi_headers: "true"
    fprocess: node server.js
    mode: http
    upstream_url: "http://127.0.0.1:3000"
    exec_timeout: 10s
    write_timeout: 15s
    read_timeout: 15s
    prefix_logs: "false"
