services:
  app:
    image: lenra/my-app
    build:
      context: ..
      dockerfile: .lenra/Dockerfile
    depends_on:
      devtool:
        condition: service_healthy
  devtool:
    healthcheck:
      test:
      - CMD
      - wget
      - --spider
      - -q
      - http://localhost:4000
      interval: 10s
      timeout: 5s
      retries: 5
    image: lenra/devtools:local
    ports:
    - 4000:4000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lenra_devtool
      POSTGRES_HOST: postgres
      OF_WATCHDOG_URL: http://app:8080
      LENRA_API_URL: http://devtool:4000
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    healthcheck:
      test:
      - CMD
      - pg_isready
      - -U
      - postgres
      interval: 5s
      retries: 5
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lenra_devtool
